### PR TITLE
Add properties reader and refactor others to attr_*

### PR DESCRIPTION
**Pull request by ur5us**

### CODE REVIEW

**Review by fonji — APPROVED** [review]
Thanks! @Intrepidd what do you think?

**Review by Intrepidd — APPROVED** [review]
Fine by me, thanks !

**Comment by ur5us** [comment]
@fonji @Intrepidd Thanks for merging that. That’ll hopefully be enough to migrate from our custom fork to this. Any plans to make a tiny release?

I have a few questions about the new organisation structure and potential follow-up PRs if you’re interested.

1. It looks like Captain Contrat is committed to offering HubSpot services and by extension to maintain this new gem going forward. This is great, thanks for that. Yet, I was wondering whether you’d be open to move the repo under a new GitHub organisation (maybe _HubSpotFriends_ or _HubspotApiRuby_ (though  HS probably won’t like that) as _HubspotCommunity_ is already taken) and potentially add more core committers from outside Captain Contrat over time to prevent history repeating itself as was the case with https://github.com/HubspotCommunity/hubspot-ruby. 

2. Other than that, I was wondering whether you’d be open to the following code changes/PRs (no promises though):
- refactor `class Hubspot::Contact`/`Module::Class` to its nested form so that constant lookup works as expected, i.e. get rid of all the `Hubspot::` namespacing on the calling side, e.g. `Hubspot::Connection.get_json(…)` → `Connection.get_json(…)` et al.. It’d simplify working with the code base IMO
- improve general formatting, maybe via RuboCop (or a specific preset like [testdouble/standard](https://github.com/testdouble/standard))
- raise the Ruby version to `>= 2.6`
- I’m not sure about the whole `Resource#add_accessors` thing. [Hashie](https://github.com/hashie/hashie) could be a better way of doing it

3. This is the least important one but would you be open to [Hacktoberfest](https://hacktoberfest.com)? I like to participate and in the process encourage other developers new to open sourcing their work to participate also, e.g. at our [local Ruby meetup](https://www.meetup.com/aucklandruby/events/289098048/). As maintainers you could do a few things to attract contributions, e.g. apply **hacktoberfest** labels to certain issues, and the same label to the repo itself, s. [guidelines](https://hacktoberfest.com/participation/#maintainers) or later apply the **hacktoberfest-accepted** label to accepted PRs. Though I understand if you’re not interested.

**Comment by Intrepidd** [comment]
Fine for me to cut a release :) @fonji do you want to do it or can I ?

Regarding `1.`, while @fonji is, I'm not from captaincontrat but my company uses this gem intensively too. I'm new in the maintainers but I am totally open to move it to a custom organisation and include more maintainers.

Regarding `2.` : Those seem to be great QOL updates :) I'm pretty much ok with all of them except maybe hashie but just because I have PTSD with it, but we can talk it through

Regarding `3.` : Need to look into it especially regarding time commitment 

Thanks !

**Comment by fonji** [comment]
> Fine for me to cut a release :) @fonji do you want to do it or can I ?

Didn't I release just after merging?
https://github.com/captaincontrat/hubspot-api-ruby/commit/04df268822f07e8c5542eb1b9be7c9cecd75a4e5
https://rubygems.org/gems/hubspot-api-ruby/versions/0.12.0
When I download the latest version, your changes seem to be included.
Let me know if I messed something up.

Regarding `1.`, seems like the way to go. I'm a bit hesitant because having the company's name in there was a justification for the time invested. I wouldn't be surprised if I become less invested if this goes out.

Regarding `2.`
> - refactor `class Hubspot::Contact`/`Module::Class` to its nested form so that constant lookup works as expected, i.e. get rid of all the `Hubspot::` namespacing on the calling side, e.g. `Hubspot::Connection.get_json(…)` → `Connection.get_json(…)` et al.. It’d simplify working with the code base IMO

Fine by me as long as we do not change the interface to the outside world.

> - improve general formatting, maybe via RuboCop (or a specific preset like [testdouble/standard](https://github.com/testdouble/standard))

Yes please! I didn't do it because I got lazy. (I'm more on the RuboCop side than standard myself, btw)

> - raise the Ruby version to `>= 2.6`

No problem with that. We're running on 3.0 and 3.1, the oldest version wasn't changed because it works.

> - I’m not sure about the whole `Resource#add_accessors` thing. [Hashie](https://github.com/hashie/hashie) could be a better way of doing it

Not sure about that, I'm curious though!

Regarding `3.` I'm also reserved about time commitment. One or two PRs is fine but I don't see myself managing 10 of those quickly :sweat_smile: 

Thanks for all of this @ur5us!

**Comment by ur5us** [comment]
@fonji Sorry for the late reply. Yes, you did actually release it. I just hadn’t noticed it because you were so quick :)

1. Another way of preserving the company sponsorship would to add a “Sponsors” section to the README and call them out specifically. It would probably even increase their visibility. I’ll leave that up to you to decide. Just trying to reduce work for everybody in case the company drops their sponsorship.
2. I’ll try to find the some time to add RuboCop and refactor the module syntax over the next 2 weeks. Other than that, I’m not sure about Hashie either, yet. I’ll only attempt to provide a PR if it actually solves a problem.
3. No problem. For what it’s worth, I’ve added the tag to [PublicActivity](https://github.com/public-activity/public_activity) but so far not a single PR for Hacktoberfest :')

**Comment by fonji** [comment]
1. OK let's do this. If more and more companies invest time in this gem, it seems fair to have the same level of recognition for them.

What about `HubspotRubyCommunity` ?

**Comment by ur5us** [comment]
@fonji It looks like the above plan never manifested, or? Is this gem abandoned given that HubSpot is retiring the v1 API in less than 2 weeks.

**Comment by fonji** [comment]
Hi @ur5us,
You're right, we never changed the repository.
This gem is still heavily in use on our side, but we missed the sunset announcement. So thank you for the heads-up!

I'll be working on it this week, [focusing on this announcement for the contacts API](https://developers.hubspot.com/changelog/extension-contact-lists-api-v1-sunset-moved-to-april-30-2026), and will keep you posted.

**Comment by fonji** [comment]
@ur5us and anyone reading here: you can check out #31 for contact lists update

**Pull request merged**
