### PR TITLE
changes need to make the gem compatible with ruby 2.4

### PR DESCRIPTION
**Pull request by sensadrome**
Since it's not actually using many new features it seems reasonable to have further coverage of older versions (for now!)

### CODE REVIEW

**Comment by Intrepidd** [comment]
I'd rather avoid adding support for such an old version (released 8 years ago) only to most likely remove it in the near future.

As we already support the 2.x branch with 2.7, which should not be too hard to migrate to from 2.4, I feel like it's good enough.

**Comment by fonji** [comment]
OK I'm convinced, closing as it is not the path forward.
Sorry @sensadrome, I hope it will give you a new reason to upgrade.

**Comment by sensadrome** [comment]
no problem @Intrepidd - and I actually think you are right by the way! I just had an old project running on 2.4 that needed to talk to hubspot. When I looked at the gem here it appeared that yield_self was the only impediment to making it work! 

As it happens I started a new gem to use v3 of the api, inspired by this one! 

https://github.com/sensadrome/ruby_hubspot_api

**Comment by fonji** [comment]
> As it happens I started a new gem to use v3 of the api, inspired by this one!

Oh cool, good to know! Thanks for the link.

**Pull request closed without merging**
